### ISSUE TITLE
Already part of ESLint core?

### ISSUE THREAD

**Issue by j-f1** [suchipi/eslint-plugin-esquery#1]
This looks pretty similar to the ESLint core rule [`no-restricted-syntax`](https://eslint.org/docs/rules/no-restricted-syntax), although the addition of the warning and error variants is a neat idea!

**Comment by suchipi** [comment]
Oh, I didn't know that supported esquery strings, neat! Thanks for the heads up, lol.

**Comment by j-f1** [comment]
Additionally, the keys of the object returned by rules’ `create` methods are also esqueries, so you can do something like `ClassDeclaration[superClass] MethodDefinition[key.name="constructor"]` to, for example, match constructors of classes that extend other classes.

**Comment by karlhorky** [comment]
Opened a PR to add this to the top of the readme, so that this is brought to the attention of users: https://github.com/suchipi/eslint-plugin-esquery/pull/10
